[package]
name = "file_shred"
version = "1.1.1"
description = "Library and binary to securily delete files, overwriting and moving them before removal."
authors = ["Mark <mverleg.noreply@gmail.com>"]
homepage = "https://github.com/mverleg/file_shred"
repository = "https://github.com/mverleg/file_shred"
readme = "README.md"
license = "BSD-3-Clause"
keywords = ["files"]
edition = "2018"

[lib]
name = "file_shred"
path = "src/lib.rs"

[[bin]]
name = "shred"
path = "src/main.rs"

[dependencies]
filetime = "^0.2.13"
indicatif = "^0.15.0"
number2name = "^1.1.2"
rand = "^0.8.0"
structopt = { version = "^0.3.21", default-features = false }

[dev-dependencies]
tempfile = "^3.1.0"

[profile.release]
lto = 'thin'
opt-level = 3

[profile.dev.package."*"]
opt-level = 3
debug = false
