[package]
name = "file_shred"
version = "1.0.0"
authors = ["Mark <mverleg.noreply@gmail.com>"]
edition = "2018"

[lib]
name = "file_shred"
path = "src/lib.rs"

[[bin]]
name = "shred"
path = "src/main.rs"

[dependencies]
structopt = { version = "^0.3.7", default-features = false }
data-encoding = "^2.1.2"
filetime = "^0.2.8"
rand = "^0.7.2"
tempfile = "^3.1.0"
number2name = "1.0.0"
